name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code-quality:
    env:
      COMPOSER_CACHE_DIR: .cache/composer
      
    runs-on: ubuntu-latest
    name: üîç Code Quality (Pint & Stan)
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
        coverage: none

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Pint (Code Style)
      run: ./vendor/bin/pint --test

    - name: PHPStan (Static Analysis)
      run: ./vendor/bin/phpstan analyse --memory-limit=2G

  tests:
    env:
      COMPOSER_CACHE_DIR: .cache/composer

    runs-on: ubuntu-latest
    name: Unit & Feature Tests
    # needs: code-quality 
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
        coverage: none

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate Key
      run: cp .env.example .env && php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: touch database/database.sqlite
        
    - name: Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: ./vendor/bin/pest